// default package
// Generated 11/02/2015 10:46:16 by Hibernate Tools 3.4.0.CR1

/**
 * CourseId generated by hbm2java
 */
public class CourseId implements java.io.Serializable {

	private int idCourse;
	private int teacherIdTeacher;

	public CourseId() {
	}

	public CourseId(int idCourse, int teacherIdTeacher) {
		this.idCourse = idCourse;
		this.teacherIdTeacher = teacherIdTeacher;
	}

	public int getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(int idCourse) {
		this.idCourse = idCourse;
	}

	public int getTeacherIdTeacher() {
		return this.teacherIdTeacher;
	}

	public void setTeacherIdTeacher(int teacherIdTeacher) {
		this.teacherIdTeacher = teacherIdTeacher;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseId))
			return false;
		CourseId castOther = (CourseId) other;

		return (this.getIdCourse() == castOther.getIdCourse())
				&& (this.getTeacherIdTeacher() == castOther
						.getTeacherIdTeacher());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCourse();
		result = 37 * result + this.getTeacherIdTeacher();
		return result;
	}

}
