// default package
// Generated 11/02/2015 10:46:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer regNumber;
	private String firstName;
	private String lastName;
	private Date dateOfBirth;

	public Student() {
	}

	public Student(String firstName, String lastName, Date dateOfBirth) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.dateOfBirth = dateOfBirth;
	}

	public Integer getRegNumber() {
		return this.regNumber;
	}

	public void setRegNumber(Integer regNumber) {
		this.regNumber = regNumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

}
