/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import DAO.ChoferDAO;
import DAO.MovilDAO;
import DAO.TurnoDAO;
import com.sun.glass.events.KeyEvent;
import entidades.Chofer;
import entidades.Movil;
import java.text.SimpleDateFormat;
import static java.time.Clock.system;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static presentacion.RendicionChofer.jtf_Movil;

/**
 *
 * @author Cristian
 */
public class LoginChofer extends javax.swing.JFrame {

    /**
     * Creates new form LoginChofer
     */
    public LoginChofer() {
        initComponents();
         this.setLocationRelativeTo(null);
        //jl_Fecha.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_DNI = new javax.swing.JTextField();
        jl_turno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl_Fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl_faltanRendir = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jl_cantidadMoviles = new javax.swing.JLabel();

        jLabel5.setText("FALTAN:");

        jLabel7.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("100 Moviles");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selección de chofer");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Terminar Rendicion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("DNI");

        jtf_DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_DNIActionPerformed(evt);
            }
        });
        jtf_DNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_DNIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_DNIKeyTyped(evt);
            }
        });

        jl_turno.setText("<Turno>");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("TURNO:");

        jl_Fecha.setText("jLabel2");

        jLabel2.setText("FALTAN RENDIR:");

        jl_faltanRendir.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jl_faltanRendir.setForeground(new java.awt.Color(255, 0, 51));
        jl_faltanRendir.setText("100");

        jLabel6.setText("CANTIDAD DE MOVILES:");

        jl_cantidadMoviles.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jl_cantidadMoviles.setForeground(new java.awt.Color(255, 0, 51));
        jl_cantidadMoviles.setText("100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_turno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_Fecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_DNI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_cantidadMoviles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_faltanRendir)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_turno)
                    .addComponent(jLabel3)
                    .addComponent(jl_Fecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_cantidadMoviles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jl_faltanRendir)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_DNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_DNIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jtf_DNI.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar el DNI de un chofer");
        }else{
            nuevaRendicion();  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea terminar la rendición");
        
        if(showConfirmDialog==0){
            this.dispose();
        }
           
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtf_DNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_DNIKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_DNIKeyTyped

    private void jtf_DNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_DNIKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                nuevaRendicion();
        }
    }//GEN-LAST:event_jtf_DNIKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginChofer().setVisible(true);
            }
        });
    }
    public void nuevaRendicion(){
        ChoferDAO choferDAO = new ChoferDAO();
        Chofer chofer = new Chofer(); 
        chofer = choferDAO.consultarChofer(Integer.parseInt(jtf_DNI.getText()));
        //jl_chofer.setText();
        if (chofer.getDNI()==0){
            jtf_DNI.setText("");
            JOptionPane.showMessageDialog(null, "Chofer no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            jtf_DNI.requestFocus();
        } else {
            RendicionChofer rendicion= new RendicionChofer();
            rendicion.setVisible(true);
            RendicionChofer.jl_Tipo.setText(jl_turno.getText());
            RendicionChofer.jl_DNI.setText(jtf_DNI.getText());
            RendicionChofer.jl_chofer.setText(chofer.getApellido()+", "+chofer.getNombre());
            RendicionChofer.nombre=chofer.getApellido()+", "+chofer.getNombre();
            RendicionChofer.jl_Fecha.setText(jl_Fecha.getText());
            TurnoDAO turnoDAO = new TurnoDAO();
            ArrayList<Movil> moviles = new ArrayList<Movil>();
            moviles = turnoDAO.obtenerMovilesSinRendicion(jl_Fecha.getText());//TO DO
        
            RendicionChofer.jtf_Movil.addItem("");
            for(Movil auto : moviles){
                RendicionChofer.jtf_Movil.addItem(auto.getIdMovil());
            }
                jtf_DNI.setText("");
                this.dispose();
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel jl_Fecha;
    public static javax.swing.JLabel jl_cantidadMoviles;
    public static javax.swing.JLabel jl_faltanRendir;
    public static javax.swing.JLabel jl_turno;
    private javax.swing.JTextField jtf_DNI;
    // End of variables declaration//GEN-END:variables
}
