/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import DAO.ChoferDAO;
import DAO.TurnoDAO;
import com.sun.glass.events.KeyEvent;
import entidades.Chofer;
import entidades.Movil;
import entidades.Turno;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class RendicionChofer extends javax.swing.JFrame {

    /**
     * Creates new form RendiciónChofer
     */
    public RendicionChofer() {
        initComponents();
        this.setLocationRelativeTo(null);
        Calendar calendario = Calendar.getInstance();
        String fechaHoraSQL = new StringBuilder()
                .append(Integer.toString(calendario.get(Calendar.DATE))).append("/")
                .append(Integer.toString(calendario.get(Calendar.MONTH)+1)).append("/")
                .append(Integer.toString(calendario.get(Calendar.YEAR))).toString();
        jl_Fecha.setText(fechaHoraSQL);
        TurnoDAO turnoDAO = new TurnoDAO();
        ArrayList<Movil> moviles = new ArrayList<Movil>();
        moviles = turnoDAO.obtenerMovilesSinRendicion("TODO");
        jtf_Movil.addItem("");
        for(Movil auto : moviles){
            jtf_Movil.addItem(auto.getIdMovil());
        }
    }
    private void registrarTurno() {
        TurnoDAO turnoDAO = new TurnoDAO();
        Turno turno = new Turno();
        
        turno.setGastosVarios(Double.parseDouble(jtf_Gastos.getText()));
        turno.setRecaudacion(Double.parseDouble(jtf_Recaudacion.getText()));
        turno.setKmInicial(Integer.parseInt(jtf_KmInicial.getText()));
        turno.setKmFinal(Integer.parseInt(jtf_KmFinal.getText()));
        turno.setTicketRelevo1(jtf_TicketRelevo1.getText());
        
        if (jl_Tipo.getText().equals("Primer Turno")) {
             turno.setTipo("P"); 
        } else if (jl_Tipo.getText().equals("Segundo Turno")) {
            turno.setTipo("S");
        }
        
        //turno.setMovil_idMovil(Integer.parseInt(jtf_Movil.getText()));
        turno.setNovedades(jta_Novedades.getText());
        turnoDAO.altaTurno(turno,jl_DNI.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_Gastos2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtf_KmInicial = new javax.swing.JTextField();
        jtf_TicketRelevo1 = new javax.swing.JTextField();
        jtf_GNCFuera = new javax.swing.JTextField();
        jtf_KmOcupados = new javax.swing.JTextField();
        jtf_KmLibres = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtf_GastosChequera = new javax.swing.JTextField();
        jtf_Recaudacion = new javax.swing.JTextField();
        jtf_Gastos = new javax.swing.JTextField();
        jtf_KmFinal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtf_TicketRelevo2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtf_GNCBruto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Novedades = new javax.swing.JTextArea();
        jtf_Movil = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtf_Comision = new javax.swing.JTextField();
        jtf_Neto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_Fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl_Tipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jl_chofer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jl_DNI = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        jtf_Gastos2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_Gastos2FocusLost(evt);
            }
        });
        jtf_Gastos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Gastos2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rendicion chofer");
        setResizable(false);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtf_KmInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_KmInicialActionPerformed(evt);
            }
        });
        jtf_KmInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_KmInicialKeyTyped(evt);
            }
        });

        jtf_TicketRelevo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_TicketRelevo1KeyTyped(evt);
            }
        });

        jtf_GNCFuera.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_GNCFueraFocusLost(evt);
            }
        });
        jtf_GNCFuera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_GNCFueraActionPerformed(evt);
            }
        });
        jtf_GNCFuera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_GNCFueraKeyTyped(evt);
            }
        });

        jtf_KmOcupados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_KmOcupadosFocusLost(evt);
            }
        });
        jtf_KmOcupados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_KmOcupadosActionPerformed(evt);
            }
        });
        jtf_KmOcupados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_KmOcupadosKeyTyped(evt);
            }
        });

        jtf_KmLibres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_KmLibresFocusLost(evt);
            }
        });
        jtf_KmLibres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_KmLibresActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setText("Gastos chequeras");

        jtf_GastosChequera.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_GastosChequeraFocusLost(evt);
            }
        });
        jtf_GastosChequera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_GastosChequeraActionPerformed(evt);
            }
        });

        jtf_Recaudacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_RecaudacionFocusLost(evt);
            }
        });
        jtf_Recaudacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_RecaudacionKeyTyped(evt);
            }
        });

        jtf_Gastos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_GastosFocusLost(evt);
            }
        });
        jtf_Gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_GastosActionPerformed(evt);
            }
        });
        jtf_Gastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_GastosKeyTyped(evt);
            }
        });

        jtf_KmFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_KmFinalFocusLost(evt);
            }
        });
        jtf_KmFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_KmFinalKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Movil");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Km Inicial");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("Tickets Relevo 1");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Recaudación");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("Tickets Relevo 2");

        jtf_TicketRelevo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_TicketRelevo2KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel16.setText("GNC bruto cuenta corriente");

        jtf_GNCBruto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf_GNCBrutoFocusLost(evt);
            }
        });
        jtf_GNCBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_GNCBrutoActionPerformed(evt);
            }
        });
        jtf_GNCBruto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_GNCBrutoKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setText("GNC bruto fuera corriente");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Gastos");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel18.setText("Km ocupados");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Km Final");

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel19.setText("Km libres");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setText("NOVEDADES");

        jta_Novedades.setColumns(20);
        jta_Novedades.setRows(3);
        jta_Novedades.setTabSize(3);
        jScrollPane1.setViewportView(jta_Novedades);

        jtf_Movil.setEditable(true);
        jtf_Movil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_MovilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("*");

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel21.setText("*");

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel22.setText("*");

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel23.setText("*");

        jLabel24.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel24.setText("*");

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel25.setText("*");

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel26.setText("*");

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel27.setText("*");

        jLabel28.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel28.setText("*");

        jLabel29.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel29.setText("*");

        jLabel30.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel30.setText("*");

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel31.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtf_GNCBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtf_Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtf_Recaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtf_TicketRelevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_KmInicial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                    .addComponent(jtf_KmOcupados, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_GastosChequera, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_Movil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel31)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel29))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(96, 96, 96)
                                                        .addComponent(jtf_TicketRelevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jtf_KmFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel24)
                                                    .addComponent(jLabel25)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel19))
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jtf_KmLibres, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel30))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jtf_GNCFuera, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel28))))))))))
                    .addComponent(jLabel14))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_Movil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_KmInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel13)
                    .addComponent(jtf_KmFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel9)
                    .addComponent(jtf_Recaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel8)
                    .addComponent(jtf_TicketRelevo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jtf_TicketRelevo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel11))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtf_GNCFuera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_GNCBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel16))))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jtf_KmOcupados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_KmLibres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtf_GastosChequera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(84, 84, 84))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("Comision");

        jtf_Comision.setEditable(false);

        jtf_Neto.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText("Neto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jtf_Comision, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jtf_Neto, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jtf_Neto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        jl_Fecha.setText("12/12/2015");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Turno:");

        jl_Tipo.setText("Primer Turno");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Chofer:");

        jl_chofer.setText("<Chofer>");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("DNI:");

        jl_DNI.setText("33050305");

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel32.setText("Los campos obligatorios estan marcados con *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 749, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jl_Fecha)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jl_Tipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jl_chofer)
                            .addGap(98, 98, 98)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jl_DNI))
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jl_Fecha)
                    .addComponent(jLabel3)
                    .addComponent(jl_Tipo)
                    .addComponent(jLabel6)
                    .addComponent(jl_chofer)
                    .addComponent(jLabel5)
                    .addComponent(jl_DNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_GastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_GastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_GastosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jta_Novedades.setText(null);
        jtf_Comision.setText(null);
        jtf_GNCBruto.setText(null);
        jtf_GNCFuera.setText(null);
        jtf_Gastos.setText(null);
        jtf_Gastos2.setText(null);
        jtf_GastosChequera.setText(null);
        jtf_KmFinal.setText(null);
        jtf_KmInicial.setText(null);
        jtf_KmLibres.setText(null);
        jtf_KmOcupados.setText(null);
        jtf_Neto.setText(null);
        jtf_Recaudacion.setText(null);
        jtf_TicketRelevo1.setText(null);
        jtf_TicketRelevo2.setText(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(jtf_KmInicial.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_KmFinal.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_Recaudacion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_TicketRelevo1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_TicketRelevo2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_Gastos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_GNCBruto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_GNCFuera.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_KmOcupados.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_KmLibres.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jtf_GastosChequera.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        
        registrarTurno();
        LoginChofer login= new LoginChofer();
        LoginChofer.jl_turno.setText(jl_Tipo.getText());
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtf_RecaudacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_RecaudacionFocusLost
        // TODO add your handling code here:
        if (jtf_Recaudacion.getText().length()>0){
            try{
                Double recaudacion = Double.parseDouble(jtf_Recaudacion.getText());
                jtf_Comision.setText(Double.toString(recaudacion*0.35));
            } catch(Exception e) {
                jtf_Recaudacion.setText("");
                jtf_Comision.setText("");
            }
        } 
    }//GEN-LAST:event_jtf_RecaudacionFocusLost

    private void jtf_GastosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_GastosFocusLost
      if (jtf_Recaudacion.getText().length()>0 && jtf_Comision.getText().length()>0 && jtf_Gastos.getText().length()>0 ){
            try{
                Double recaudacion = Double.parseDouble(jtf_Recaudacion.getText());
                Double comision = Double.parseDouble(jtf_Comision.getText());
                Double gastos = Double.parseDouble(jtf_Gastos.getText());
                jtf_Neto.setText(Double.toString(recaudacion-comision-gastos));
            } catch(Exception e) {
                jtf_Recaudacion.setText("");
                jtf_Comision.setText("");
                jtf_Gastos.setText("");
            }
        } 
    }//GEN-LAST:event_jtf_GastosFocusLost

    private void jtf_GNCBrutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_GNCBrutoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_GNCBrutoFocusLost

    private void jtf_GNCBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_GNCBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_GNCBrutoActionPerformed

    private void jtf_Gastos2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_Gastos2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Gastos2FocusLost

    private void jtf_Gastos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Gastos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Gastos2ActionPerformed

    private void jtf_GNCFueraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_GNCFueraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_GNCFueraFocusLost

    private void jtf_GNCFueraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_GNCFueraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_GNCFueraActionPerformed

    private void jtf_KmOcupadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_KmOcupadosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_KmOcupadosFocusLost

    private void jtf_KmOcupadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_KmOcupadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_KmOcupadosActionPerformed

    private void jtf_KmLibresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_KmLibresFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_KmLibresFocusLost

    private void jtf_KmLibresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_KmLibresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_KmLibresActionPerformed

    private void jtf_GastosChequeraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_GastosChequeraFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_GastosChequeraFocusLost

    private void jtf_GastosChequeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_GastosChequeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_GastosChequeraActionPerformed

    private void jtf_MovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_MovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_MovilActionPerformed

    private void jtf_KmInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_KmInicialActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtf_KmInicialActionPerformed

    private void jtf_KmInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_KmInicialKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_KmInicial.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtf_KmInicialKeyTyped

    private void jtf_KmFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_KmFinalKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_KmFinal.getText().contains(".")) {
                evt.consume();
            }
        }

    }//GEN-LAST:event_jtf_KmFinalKeyTyped

    private void jtf_RecaudacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_RecaudacionKeyTyped
        // TODO add your handling code here:
        if  (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_Recaudacion.getText().contains(".")) {
                evt.consume();
            }
    }//GEN-LAST:event_jtf_RecaudacionKeyTyped
    }
    private void jtf_TicketRelevo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_TicketRelevo1KeyTyped
        // TODO add your handling code here:
        if  (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_TicketRelevo1.getText().contains(".")) {
                evt.consume();
            }
        }    
    }//GEN-LAST:event_jtf_TicketRelevo1KeyTyped

    private void jtf_TicketRelevo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_TicketRelevo2KeyTyped
        // TODO add your handling code here:
        if  (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_TicketRelevo2.getText().contains(".")) {
                evt.consume();
            }
        }
        
    }//GEN-LAST:event_jtf_TicketRelevo2KeyTyped

    private void jtf_GastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_GastosKeyTyped
        // TODO add your handling code here:
        if  (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_Gastos.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtf_GastosKeyTyped

    private void jtf_GNCBrutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_GNCBrutoKeyTyped
        // TODO add your handling code here:
        if  (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_GNCBruto.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtf_GNCBrutoKeyTyped

    private void jtf_GNCFueraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_GNCFueraKeyTyped
        // TODO add your handling code here:
        if  (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_GNCFuera.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtf_GNCFueraKeyTyped

    private void jtf_KmOcupadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_KmOcupadosKeyTyped
        // TODO add your handling code here:
        if  (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
            if (evt.getKeyChar() == '.' && jtf_KmOcupados.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtf_KmOcupadosKeyTyped

    private void jtf_KmFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_KmFinalFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtf_KmFinalFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RendicionChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RendicionChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RendicionChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RendicionChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RendicionChofer().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel jl_DNI;
    private javax.swing.JLabel jl_Fecha;
    public static javax.swing.JLabel jl_Tipo;
    public static javax.swing.JLabel jl_chofer;
    private javax.swing.JTextArea jta_Novedades;
    private javax.swing.JTextField jtf_Comision;
    private javax.swing.JTextField jtf_GNCBruto;
    private javax.swing.JTextField jtf_GNCFuera;
    private javax.swing.JTextField jtf_Gastos;
    private javax.swing.JTextField jtf_Gastos2;
    private javax.swing.JTextField jtf_GastosChequera;
    private javax.swing.JTextField jtf_KmFinal;
    private javax.swing.JTextField jtf_KmInicial;
    private javax.swing.JTextField jtf_KmLibres;
    private javax.swing.JTextField jtf_KmOcupados;
    private javax.swing.JComboBox jtf_Movil;
    private javax.swing.JTextField jtf_Neto;
    private javax.swing.JTextField jtf_Recaudacion;
    private javax.swing.JTextField jtf_TicketRelevo1;
    private javax.swing.JTextField jtf_TicketRelevo2;
    // End of variables declaration//GEN-END:variables
}
