/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import DAO.MovilDAO;
import entidades.Movil;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class VentanaMovil extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMovil
     */
    public VentanaMovil() {
        initComponents();
        this.setLocationRelativeTo(null);
        verTodos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt_movil = new javax.swing.JTable();
        jb_ActionNuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jte_nroMovil = new javax.swing.JTextField();
        jb_ActionBuscar = new javax.swing.JButton();
        jb_verTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jt_movil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. Movil", "Patente", "Nro. Licencia", "Kilometraje", "Modelo", "Fecha Vto. Licencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_movil);

        jb_ActionNuevo.setText("Nuevo");
        jb_ActionNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ActionNuevoActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Nro. Movil");

        jb_ActionBuscar.setText("Buscar");
        jb_ActionBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ActionBuscarActionPerformed(evt);
            }
        });

        jb_verTodos.setText("Ver Todos");
        jb_verTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_verTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jte_nroMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_ActionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_verTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_ActionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addComponent(jte_nroMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ActionBuscar)
                    .addComponent(jb_ActionNuevo)
                    .addComponent(jb_verTodos))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_ActionNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ActionNuevoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ABMMovil abmmovil=new ABMMovil();
        abmmovil.setVisible(true);
    }//GEN-LAST:event_jb_ActionNuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jb_ActionBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ActionBuscarActionPerformed
        // TODO add your handling code here:
        MovilDAO movilDAO = new MovilDAO();
        ArrayList<Movil> moviles = new ArrayList<Movil>();
        DefaultTableModel modelo = (DefaultTableModel) jt_movil.getModel();
        modelo.setNumRows(0);
        int nroMovil;
        try {
            nroMovil = Integer.parseInt(jte_nroMovil.getText());
            if (nroMovil == 0 || nroMovil < 0 ){
                JOptionPane.showMessageDialog(null, "Ingrese un DNI valido.", "Error", JOptionPane.ERROR_MESSAGE);
                jte_nroMovil.setText("");
                jte_nroMovil.requestFocus();
            }
            moviles = movilDAO.obtenerIdMoviles();
            for (Movil movil: moviles){
                String[] datos = {
                    String.valueOf(movil.getIdMovil()),
                    movil.getPatente(),
                    movil.getModelo(),
                    movil.getLicencia(),
                    String.valueOf(movil.getNumeroLicencia()),
                    String.valueOf(movil.getKilometraje())};
                modelo.addRow(datos);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese un Movil valido.", "Error", JOptionPane.ERROR_MESSAGE);
            jte_nroMovil.setText("");
            jte_nroMovil.requestFocus();
        }
    
    }//GEN-LAST:event_jb_ActionBuscarActionPerformed

    private void jb_verTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_verTodosActionPerformed
        // TODO add your handling code here:
        verTodos();
    }//GEN-LAST:event_jb_verTodosActionPerformed

    public void verTodos(){
        MovilDAO movilDAO = new MovilDAO();
        ArrayList<Movil> moviles = new ArrayList<Movil>();
        DefaultTableModel modelo = (DefaultTableModel) jt_movil.getModel();
        modelo.setNumRows(0);
        moviles = movilDAO.getMoviles();
        for (Movil movil: moviles){
            String[] datos = {
                String.valueOf(movil.getIdMovil()),
                movil.getModelo(),
                movil.getPatente(),
                movil.getLicencia(),
                movil.getFechaLicencia(),
                String.valueOf(movil.getKilometraje()),
                };
            modelo.addRow(datos);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_ActionBuscar;
    private javax.swing.JButton jb_ActionNuevo;
    private javax.swing.JButton jb_verTodos;
    private javax.swing.JTable jt_movil;
    private javax.swing.JTextField jte_nroMovil;
    // End of variables declaration//GEN-END:variables
}
