/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import DAO.ChoferDAO;
import com.sun.glass.events.KeyEvent;
import entidades.Chofer;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class VentanaChofer extends javax.swing.JFrame {

    /**
     * Creates new form ChoferWindow
     */
    public VentanaChofer() {
        initComponents();
        this.setLocationRelativeTo(null);
        verTodos();
            
    }
    public void verTodos(){
        ChoferDAO choferDAO = new ChoferDAO();
        ArrayList<Chofer> choferes = new ArrayList<Chofer>();
        DefaultTableModel modelo = (DefaultTableModel) jt_Chofer.getModel();
        modelo.setNumRows(0);
        choferes = choferDAO.getChoferes();
        for (Chofer chofer: choferes){
            String[] datos = {
                String.valueOf(chofer.getDNI()),
                chofer.getApellido()+", "+chofer.getNombre(),
                chofer.getTelefono(),
                chofer.getCelular(),
                toFecha(chofer.getFechaCarnetVencimiento()),
                chofer.getDomicilio()};
            modelo.addRow(datos);
        }
    }
    public String toFecha(String fecha){
        return fecha.substring(8)+"-"+fecha.substring(5, 7)+"-"+fecha.substring(0, 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jb_Nuevo = new javax.swing.JButton();
        jb_Buscar = new javax.swing.JButton();
        jtf_DNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Chofer = new javax.swing.JTable();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        popupMenu.add(Modificar);

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        popupMenu.add(Borrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jb_Nuevo.setText("Nuevo");
        jb_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_NuevoActionPerformed(evt);
            }
        });

        jb_Buscar.setText("Buscar");
        jb_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BuscarActionPerformed(evt);
            }
        });

        jtf_DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_DNIActionPerformed(evt);
            }
        });
        jtf_DNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_DNIKeyTyped(evt);
            }
        });

        jLabel1.setText("DNI");

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Ver todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Nuevo)
                    .addComponent(jb_Buscar)
                    .addComponent(jtf_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jt_Chofer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Nombre", "Telefono fijo", "Telefono Celular", "Vencimiento Carnet", "Domicilio"
            }
        ));
        jt_Chofer.setComponentPopupMenu(popupMenu);
        jScrollPane1.setViewportView(jt_Chofer);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_NuevoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ABMChofer abmchofer= new ABMChofer();
        ABMChofer.jb_Guardar.setEnabled(true);
        ABMChofer.jb_Modificar.setVisible(false);
        abmchofer.setVisible(true);
    }//GEN-LAST:event_jb_NuevoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtf_DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_DNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_DNIActionPerformed

    private void jb_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BuscarActionPerformed
        ChoferDAO choferDAO = new ChoferDAO();
        ArrayList<Chofer> choferes = new ArrayList<Chofer>();
        DefaultTableModel modelo = (DefaultTableModel) jt_Chofer.getModel();
        modelo.setNumRows(0);
        int dni;
        try {
            dni = Integer.parseInt(jtf_DNI.getText());
            if (dni == 0 || dni < 0 ){
                JOptionPane.showMessageDialog(null, "Ingrese un DNI valido.", "Error", JOptionPane.ERROR_MESSAGE);
                jtf_DNI.setText("");
                jtf_DNI.requestFocus();
            }
            choferes = choferDAO.consultarChofer(dni);
            for (Chofer chofer: choferes){
                String[] datos = {
                    String.valueOf(chofer.getDNI()),
                    chofer.getApellido()+", "+chofer.getNombre(),
                    chofer.getTelefono(),
                    chofer.getCelular(),
                    chofer.getFechaCarnetVencimiento(),
                    chofer.getDomicilio()};
                modelo.addRow(datos);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese un DNI valido.", "Error", JOptionPane.ERROR_MESSAGE);
            jtf_DNI.setText("");
            jtf_DNI.requestFocus();
        }
    }//GEN-LAST:event_jb_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        verTodos();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jt_Chofer.getModel();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Calendar dateOtorgamiento = Calendar.getInstance();
        Calendar dateVencimiento = Calendar.getInstance();
        int fila = jt_Chofer.getSelectedRow();
        int dni = Integer.parseInt(modelo.getValueAt(jt_Chofer.getSelectedRow(), 0).toString());
        ChoferDAO choferDAO = new ChoferDAO();
        ArrayList<Chofer> choferes = new ArrayList<Chofer>();
        if (fila<0){
            JOptionPane.showMessageDialog(null,"Seleccione un chofer para realizar esta operacion.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            this.dispose();
            ABMChofer abmchofer= new ABMChofer();
            ABMChofer.jb_Modificar.setEnabled(true);
            ABMChofer.jb_Guardar.setVisible(false);
            
            choferes = choferDAO.consultarChofer(dni);
            ABMChofer.jtf_DNI.setText(String.valueOf(choferes.get(0).getDNI()));
            ABMChofer.jtf_Nombre.setText(choferes.get(0).getNombre());
            ABMChofer.jtf_Apellido.setText(choferes.get(0).getApellido());
            ABMChofer.jtf_Domicilio.setText(choferes.get(0).getDomicilio());
            ABMChofer.jtf_Localidad.setText(choferes.get(0).getLocalidad());
            ABMChofer.jtf_Provincia.setText(choferes.get(0).getProvincia());
            ABMChofer.jtf_TelefonoFijo.setText(choferes.get(0).getTelefono());
            ABMChofer.jtf_TelefonoCelular.setText(choferes.get(0).getCelular());
            ABMChofer.jtf_Categoria.setText(choferes.get(0).getCategoria());
            try {
                dateOtorgamiento.setTime(format.parse(choferes.get(0).getFechaCarnetOtorgamiento()));
                dateVencimiento.setTime(format.parse(choferes.get(0).getFechaCarnetVencimiento()));
            } catch (ParseException ex) {
                Logger.getLogger(ABMChofer.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            ABMChofer.jtf_FechaOtorgamiento.setSelectedDate(dateOtorgamiento);
            ABMChofer.jtf_FechaVencimiento.setSelectedDate(dateVencimiento);
            abmchofer.setVisible(true);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jt_Chofer.getModel();
        int fila = jt_Chofer.getSelectedRow();
        int dni = Integer.parseInt(modelo.getValueAt(jt_Chofer.getSelectedRow(), 0).toString());
        ChoferDAO choferDAO = new ChoferDAO();
        if (fila<0){
        JOptionPane.showMessageDialog(null,"Seleccione el chofer que desea borrar.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            choferDAO.eliminarChofer(dni);
            modelo.removeRow(jt_Chofer.getSelectedRow()); 
        }
    }//GEN-LAST:event_BorrarActionPerformed

    private void jtf_DNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_DNIKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_DNIKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaChofer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Borrar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.JButton jb_Nuevo;
    private javax.swing.JTable jt_Chofer;
    private javax.swing.JTextField jtf_DNI;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
